# -*- coding: utf-8 -*-
"""Sensor Node Simulator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13AOE4wnfrxQcPubYgNQjcZJLTFrww-ZR
"""

import paho.mqtt.client as mqtt
import time
import json
import random

# --- Configuration ---
MQTT_BROKER = "test.mosquitto.org"
MQTT_PORT = 1883
BASE_TOPIC = "iitbhu/mold_prevention/room"

# Define different rooms (nodes) to simulate
ROOMS = ["bathroom", "basement", "kitchen"]

# --- MQTT Client Setup ---
client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2, client_id="sensor_nodes_simulator")

def connect_mqtt():
    """Connects to the MQTT broker."""
    try:
        client.connect(MQTT_BROKER, MQTT_PORT, 60)
        print("Successfully connected to MQTT Broker!")
    except Exception as e:
        print(f"Failed to connect to MQTT Broker: {e}")
        exit()

connect_mqtt()

# --- Main Simulation Loop ---
try:
    while True:
        # Iterate through each room and generate data
        for room in ROOMS:
            # Simulate realistic sensor readings
            # The bathroom and basement will have higher humidity spikes
            if room == "bathroom":
                humidity = round(random.uniform(65.0, 85.0), 2)
            elif room == "basement":
                humidity = round(random.uniform(60.0, 78.0), 2)
            else: # Kitchen
                humidity = round(random.uniform(50.0, 75.0), 2)

            temperature = round(random.uniform(20.0, 26.0), 2)

            # Create JSON payload
            payload = json.dumps({
                "room": room,
                "temperature": temperature,
                "humidity": humidity,
                "timestamp": time.time()
            })

            # Construct the topic for the specific room
            topic = f"{BASE_TOPIC}/{room}"

            # Publish the data
            result = client.publish(topic, payload)
            # result.wait_for_publish() # Optional: wait for publish confirmation

            if result.rc == mqtt.MQTT_ERR_SUCCESS:
                print(f"Published to {topic}: Temp={temperature}°C, Humidity={humidity}%")
            else:
                print(f"Failed to publish message to topic {topic}")

        print("-" * 20)
        time.sleep(10) # Publish data for all rooms every 10 seconds

except KeyboardInterrupt:
    print("Simulation stopped by user.")
finally:
    client.disconnect()
    print("Disconnected from MQTT Broker.")
